swagger: '2.0.0'

info:
  version: '0.1.0'
  title: Facestore API
  description: foobar

  x-logo:
    url: '../assets/logo.png'
    backgroundColor: '#FFFFF'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  contact:
    name: Images upload API team
    email: luciano@lucianojr.com.br
    url: https://lucianojr.com.br

host: app.local

basePath: /v1

schemes:
  - https

consumes:
  - application/json
  - multipart/form-data

produces:
  - application/json

responses:
  401:
    description: Unauthorized
  403:
    description: Forbidden
  406:
    description: Not Acceptable
  415:
    description: Unsupported Media Type
  204:
    description: No Content Exist
    schema:
      type: array
      properties:
        code:
          type: integer
          example:
            422
        message:
          type: object
          properties:
            errors:
              type: object
              properties:
                fields:
                  type: array
  422:
    description: Content body error
    schema:
      type: object
      properties:
        code:
          type: integer
          example:
            422
        message:
          type: object
          properties:
            errors:
              type: object
              properties:
                fields:
                  type: array

tags:
  - name: images
    description: Everything about your images

paths:
  /images/:
    post:

  /images/{id}/:
    post:
      tags:
        - products
      summary: Upload de images for product
      operationId: uploadImages
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - name: id
          in: path
          description: ID of product to update
          required: true
          type: integer
          format: int64
        - name: files
          in: formData
          description: File for product
          type: file
      responses:
        200:
          description: The images has been uploaded
        404:
          description: Resource not found
          schema:
            type: object
            items:
              $ref: '#/definitions/NotFoundResponse'


definitions:

parameters:
  OrderByParam:
    name: order_by
    in: query
    description: |
      Specify the field to be sorted, examples:

      - `?order_by=id|desc`
      - `?order_by=updated_at|desc,position|asc`
    required: false
    type: array
    items:
      type: field

securityDefinitions:
  APIKeyHeader:
    type: apiKey
    in: header
    name: APIToken

security:
  - APIKeyHeader: []