language: php

php:
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env
  - mysql -e 'create database travis;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate

script:
  - vendor/bin/phpunit

script:
  - phpdbg -qrr vendor/bin/phpunit --coverage-clover=coverage.xml

services:
  - mysql

git:
  submodules: false
  
cache:
  directories:
    - vendor