language: php

php:
  - 7.1

before_script:
  - phpenv config-rm xdebug.ini
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --path=app/Domains/Uploads/Migrations

script:
  - vendor/bin/phpunit

services:
  - mysql

git:
  submodules: false

cache:
  directories:
    - vendor